version: '3'

tasks:
  dev:
    desc: Start dev server
    cmds:
      - npm run dev

  build:
    desc: Build for production
    cmds:
      - npm run build

  lint:
    desc: Type-check and lint code
    cmds:
      - npx tsc -b --noEmit
      - npm run lint