version: '3'

tasks:
  dev:
    desc: Start dev server
    cmds:
      - npm run dev

  build:
    desc: Build for production
    cmds:
      - npm run build

  lint:
    desc: Lint code
    cmds:
      - npm run lint