version: '3'

includes:
  server:
    taskfile: server/Taskfile.yml
    dir: server
  client:
    taskfile: client/Taskfile.yml
    dir: client

tasks:
  # ── Orchestration ──────────────────────────────────────────────────

  check:
    desc: Check all projects
    cmds:
      - task server:check
      - task client:lint

  test:
    desc: Run all tests
    deps: [check]
    cmds:
      - task server:test

  build:
    desc: Build all projects
    cmds:
      - task server:build
      - task client:build

  # ── Deploy ─────────────────────────────────────────────────────────

  login:
    desc: Login to Spacetime using .env token
    cmds:
      - bash tools/spacetime_login.sh

  publish:
    desc: Publish world-alpha-ikariadb to maincloud
    deps: [login, server:build]
    cmds:
      - spacetime publish -p server/bins/world-alpha-ikariadb -s maincloud -y world-alpha-ikariadb

  unsafe-overwrite:
    desc: Publish world-alpha-ikariadb to maincloud and delete data
    deps: [login, server:build]
    cmds:
      - spacetime publish -p server/bins/world-alpha-ikariadb -s maincloud -y world-alpha-ikariadb --delete-data

  publish-prod:
    desc: Publish world-draconis-ikariadb to maincloud
    deps: [login, server:build]
    cmds:
      - spacetime publish -p server/bins/world-draconis-ikariadb -s maincloud -y world-draconis-ikariadb