version: '3'

tasks:
  sdk-rust:
    desc: Generate Rust types into sdks/types/src/autogen
    cmds:
      - rm -rf sdks/types/src/autogen
      - mkdir -p sdks/types/src/autogen
      - spacetime generate --lang rust --out-dir sdks/types/src/autogen --project-path bins/world-draconis-ikariadb

  fmt:
    desc: Format all workspace code
    cmds:
      - cargo fmt --all

  check:
    desc: Check all workspace targets
    deps: [fmt]
    cmds:
      - cargo clippy --workspace --all-targets
      - cargo check --workspace --all-targets

  test:
    desc: Run all workspace tests
    deps: [check]
    cmds:
      - cargo test --workspace

  build:
    desc: Build server wasm target and host workspace targets
    cmds:
      - task sdk-rust
      - task check
      - cargo build -p world-alpha-ikariadb --target wasm32-unknown-unknown
      - cargo build -p world-draconis-ikariadb --target wasm32-unknown-unknown
      - cargo build --workspace --exclude world-alpha-ikariadb --exclude world-draconis-ikariadb

  run:
    desc: Run the ikaria client
    cmds:
      - cargo run -p ikaria

  login:
    desc: Login to Spacetime using .env token
    cmds:
      - bash tools/spacetime_login.sh

  publish:
    desc: Publish world-alpha-ikariadb to maincloud
    deps: [login, build]
    cmds:
      - spacetime publish -p bins/world-alpha-ikariadb -s maincloud -y world-alpha-ikariadb

  unsafe-overwrite:
    desc: Publish world-alpha-ikariadb to maincloud and delete data
    deps: [login, build]
    cmds:
      - spacetime publish -p bins/world-alpha-ikariadb -s maincloud -y world-alpha-ikariadb --delete-data

  publish-prod:
    desc: Publish world-draconis-ikariadb to maincloud
    deps: [login, build]
    cmds:
      - spacetime publish -p bins/world-draconis-ikariadb -s maincloud -y world-draconis-ikariadb