// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::skill_v_1_type::SkillV1;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterSkillV1 {
    pub skill_entry_id: u64,
    pub character_id: u64,
    pub skill: SkillV1,
    pub level: u16,
    pub progress_percent: u8,
}

impl __sdk::InModule for CharacterSkillV1 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterSkillV1`.
///
/// Provides typed access to columns for query building.
pub struct CharacterSkillV1Cols {
    pub skill_entry_id: __sdk::__query_builder::Col<CharacterSkillV1, u64>,
    pub character_id: __sdk::__query_builder::Col<CharacterSkillV1, u64>,
    pub skill: __sdk::__query_builder::Col<CharacterSkillV1, SkillV1>,
    pub level: __sdk::__query_builder::Col<CharacterSkillV1, u16>,
    pub progress_percent: __sdk::__query_builder::Col<CharacterSkillV1, u8>,
}

impl __sdk::__query_builder::HasCols for CharacterSkillV1 {
    type Cols = CharacterSkillV1Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterSkillV1Cols {
            skill_entry_id: __sdk::__query_builder::Col::new(table_name, "skill_entry_id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            skill: __sdk::__query_builder::Col::new(table_name, "skill"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            progress_percent: __sdk::__query_builder::Col::new(table_name, "progress_percent"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterSkillV1`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterSkillV1IxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterSkillV1, u64>,
    pub skill_entry_id: __sdk::__query_builder::IxCol<CharacterSkillV1, u64>,
}

impl __sdk::__query_builder::HasIxCols for CharacterSkillV1 {
    type IxCols = CharacterSkillV1IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterSkillV1IxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            skill_entry_id: __sdk::__query_builder::IxCol::new(table_name, "skill_entry_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterSkillV1 {}
