// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_stats_v_1_type::CharacterStatsV1;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_stats_v1`.
///
/// Obtain a handle from the [`CharacterStatsV1TableAccess::character_stats_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.character_stats_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_stats_v_1().on_insert(...)`.
pub struct CharacterStatsV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterStatsV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_stats_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterStatsV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterStatsV1TableHandle`], which mediates access to the table `character_stats_v1`.
    fn character_stats_v_1(&self) -> CharacterStatsV1TableHandle<'_>;
}

impl CharacterStatsV1TableAccess for super::RemoteTables {
    fn character_stats_v_1(&self) -> CharacterStatsV1TableHandle<'_> {
        CharacterStatsV1TableHandle {
            imp: self.imp.get_table::<CharacterStatsV1>("character_stats_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterStatsV1InsertCallbackId(__sdk::CallbackId);
pub struct CharacterStatsV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterStatsV1TableHandle<'ctx> {
    type Row = CharacterStatsV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterStatsV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterStatsV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterStatsV1InsertCallbackId {
        CharacterStatsV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterStatsV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterStatsV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterStatsV1DeleteCallbackId {
        CharacterStatsV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterStatsV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterStatsV1>("character_stats_v1");
    _table.add_unique_constraint::<u64>("character_id", |row| &row.character_id);
}
pub struct CharacterStatsV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterStatsV1TableHandle<'ctx> {
    type UpdateCallbackId = CharacterStatsV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterStatsV1UpdateCallbackId {
        CharacterStatsV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterStatsV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CharacterStatsV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterStatsV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `character_id` unique index on the table `character_stats_v1`,
/// which allows point queries on the field of the same name
/// via the [`CharacterStatsV1CharacterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_stats_v_1().character_id().find(...)`.
pub struct CharacterStatsV1CharacterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterStatsV1, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterStatsV1TableHandle<'ctx> {
    /// Get a handle on the `character_id` unique index on the table `character_stats_v1`.
    pub fn character_id(&self) -> CharacterStatsV1CharacterIdUnique<'ctx> {
        CharacterStatsV1CharacterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("character_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterStatsV1CharacterIdUnique<'ctx> {
    /// Find the subscribed row whose `character_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CharacterStatsV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterStatsV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait character_stats_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterStatsV1`.
    fn character_stats_v1(&self) -> __sdk::__query_builder::Table<CharacterStatsV1>;
}

impl character_stats_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn character_stats_v1(&self) -> __sdk::__query_builder::Table<CharacterStatsV1> {
        __sdk::__query_builder::Table::new("character_stats_v1")
    }
}
