// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::{character_v_1_type::CharacterV1, class_v_1_type::ClassV1, gender_v_1_type::GenderV1, race_v_1_type::RaceV1};
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_v1`.
///
/// Obtain a handle from the [`CharacterV1TableAccess::character_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.character_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_v_1().on_insert(...)`.
pub struct CharacterV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterV1TableHandle`], which mediates access to the table `character_v1`.
    fn character_v_1(&self) -> CharacterV1TableHandle<'_>;
}

impl CharacterV1TableAccess for super::RemoteTables {
    fn character_v_1(&self) -> CharacterV1TableHandle<'_> {
        CharacterV1TableHandle {
            imp: self.imp.get_table::<CharacterV1>("character_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterV1InsertCallbackId(__sdk::CallbackId);
pub struct CharacterV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterV1TableHandle<'ctx> {
    type Row = CharacterV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterV1InsertCallbackId;

    fn on_insert(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> CharacterV1InsertCallbackId {
        CharacterV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterV1DeleteCallbackId;

    fn on_delete(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> CharacterV1DeleteCallbackId {
        CharacterV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterV1>("character_v1");
    _table.add_unique_constraint::<u64>("character_id", |row| &row.character_id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct CharacterV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterV1TableHandle<'ctx> {
    type UpdateCallbackId = CharacterV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterV1UpdateCallbackId {
        CharacterV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CharacterV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `character_id` unique index on the table `character_v1`,
/// which allows point queries on the field of the same name
/// via the [`CharacterV1CharacterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_v_1().character_id().find(...)`.
pub struct CharacterV1CharacterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterV1, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterV1TableHandle<'ctx> {
    /// Get a handle on the `character_id` unique index on the table `character_v1`.
    pub fn character_id(&self) -> CharacterV1CharacterIdUnique<'ctx> {
        CharacterV1CharacterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("character_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterV1CharacterIdUnique<'ctx> {
    /// Find the subscribed row whose `character_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CharacterV1> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `character_v1`,
/// which allows point queries on the field of the same name
/// via the [`CharacterV1NameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_v_1().name().find(...)`.
pub struct CharacterV1NameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterV1, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterV1TableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `character_v1`.
    pub fn name(&self) -> CharacterV1NameUnique<'ctx> {
        CharacterV1NameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterV1NameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<CharacterV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait character_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterV1`.
    fn character_v1(&self) -> __sdk::__query_builder::Table<CharacterV1>;
}

impl character_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn character_v1(&self) -> __sdk::__query_builder::Table<CharacterV1> {
        __sdk::__query_builder::Table::new("character_v1")
    }
}
