// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::{character_skill_v_1_type::CharacterSkillV1, skill_v_1_type::SkillV1};
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_skill_v1`.
///
/// Obtain a handle from the [`CharacterSkillV1TableAccess::character_skill_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.character_skill_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_skill_v_1().on_insert(...)`.
pub struct CharacterSkillV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterSkillV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_skill_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterSkillV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterSkillV1TableHandle`], which mediates access to the table `character_skill_v1`.
    fn character_skill_v_1(&self) -> CharacterSkillV1TableHandle<'_>;
}

impl CharacterSkillV1TableAccess for super::RemoteTables {
    fn character_skill_v_1(&self) -> CharacterSkillV1TableHandle<'_> {
        CharacterSkillV1TableHandle {
            imp: self.imp.get_table::<CharacterSkillV1>("character_skill_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterSkillV1InsertCallbackId(__sdk::CallbackId);
pub struct CharacterSkillV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterSkillV1TableHandle<'ctx> {
    type Row = CharacterSkillV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterSkillV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterSkillV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterSkillV1InsertCallbackId {
        CharacterSkillV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterSkillV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterSkillV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterSkillV1DeleteCallbackId {
        CharacterSkillV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterSkillV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterSkillV1>("character_skill_v1");
    _table.add_unique_constraint::<u64>("skill_entry_id", |row| &row.skill_entry_id);
}
pub struct CharacterSkillV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterSkillV1TableHandle<'ctx> {
    type UpdateCallbackId = CharacterSkillV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterSkillV1UpdateCallbackId {
        CharacterSkillV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterSkillV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CharacterSkillV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterSkillV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `skill_entry_id` unique index on the table `character_skill_v1`,
/// which allows point queries on the field of the same name
/// via the [`CharacterSkillV1SkillEntryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_skill_v_1().skill_entry_id().find(...)`.
pub struct CharacterSkillV1SkillEntryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterSkillV1, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterSkillV1TableHandle<'ctx> {
    /// Get a handle on the `skill_entry_id` unique index on the table `character_skill_v1`.
    pub fn skill_entry_id(&self) -> CharacterSkillV1SkillEntryIdUnique<'ctx> {
        CharacterSkillV1SkillEntryIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("skill_entry_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterSkillV1SkillEntryIdUnique<'ctx> {
    /// Find the subscribed row whose `skill_entry_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CharacterSkillV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterSkillV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait character_skill_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterSkillV1`.
    fn character_skill_v1(&self) -> __sdk::__query_builder::Table<CharacterSkillV1>;
}

impl character_skill_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn character_skill_v1(&self) -> __sdk::__query_builder::Table<CharacterSkillV1> {
        __sdk::__query_builder::Table::new("character_skill_v1")
    }
}
