// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::direction_v_1_type::DirectionV1;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterPositionV1 {
    pub character_id: u64,
    pub x: u16,
    pub y: u16,
    pub z: u16,
    pub direction: DirectionV1,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for CharacterPositionV1 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterPositionV1`.
///
/// Provides typed access to columns for query building.
pub struct CharacterPositionV1Cols {
    pub character_id: __sdk::__query_builder::Col<CharacterPositionV1, u64>,
    pub x: __sdk::__query_builder::Col<CharacterPositionV1, u16>,
    pub y: __sdk::__query_builder::Col<CharacterPositionV1, u16>,
    pub z: __sdk::__query_builder::Col<CharacterPositionV1, u16>,
    pub direction: __sdk::__query_builder::Col<CharacterPositionV1, DirectionV1>,
    pub updated_at: __sdk::__query_builder::Col<CharacterPositionV1, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for CharacterPositionV1 {
    type Cols = CharacterPositionV1Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterPositionV1Cols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            direction: __sdk::__query_builder::Col::new(table_name, "direction"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterPositionV1`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterPositionV1IxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterPositionV1, u64>,
}

impl __sdk::__query_builder::HasIxCols for CharacterPositionV1 {
    type IxCols = CharacterPositionV1IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterPositionV1IxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterPositionV1 {}
