// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::{class_v_1_type::ClassV1, gender_v_1_type::GenderV1, race_v_1_type::RaceV1};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterV1 {
    pub character_id: u64,
    pub user_id: __sdk::Identity,
    pub name: String,
    pub display_name: String,
    pub race: RaceV1,
    pub class: ClassV1,
    pub gender: GenderV1,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for CharacterV1 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterV1`.
///
/// Provides typed access to columns for query building.
pub struct CharacterV1Cols {
    pub character_id: __sdk::__query_builder::Col<CharacterV1, u64>,
    pub user_id: __sdk::__query_builder::Col<CharacterV1, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<CharacterV1, String>,
    pub display_name: __sdk::__query_builder::Col<CharacterV1, String>,
    pub race: __sdk::__query_builder::Col<CharacterV1, RaceV1>,
    pub class: __sdk::__query_builder::Col<CharacterV1, ClassV1>,
    pub gender: __sdk::__query_builder::Col<CharacterV1, GenderV1>,
    pub created_at: __sdk::__query_builder::Col<CharacterV1, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for CharacterV1 {
    type Cols = CharacterV1Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterV1Cols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            race: __sdk::__query_builder::Col::new(table_name, "race"),
            class: __sdk::__query_builder::Col::new(table_name, "class"),
            gender: __sdk::__query_builder::Col::new(table_name, "gender"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterV1`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterV1IxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterV1, u64>,
    pub name: __sdk::__query_builder::IxCol<CharacterV1, String>,
    pub user_id: __sdk::__query_builder::IxCol<CharacterV1, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for CharacterV1 {
    type IxCols = CharacterV1IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterV1IxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}
