// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterStatsV1 {
    pub character_id: u64,
    pub user_id: __sdk::Identity,
    pub level: u16,
    pub experience: u64,
    pub health: u32,
    pub mana: u32,
    pub capacity: u32,
}

impl __sdk::InModule for CharacterStatsV1 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterStatsV1`.
///
/// Provides typed access to columns for query building.
pub struct CharacterStatsV1Cols {
    pub character_id: __sdk::__query_builder::Col<CharacterStatsV1, u64>,
    pub user_id: __sdk::__query_builder::Col<CharacterStatsV1, __sdk::Identity>,
    pub level: __sdk::__query_builder::Col<CharacterStatsV1, u16>,
    pub experience: __sdk::__query_builder::Col<CharacterStatsV1, u64>,
    pub health: __sdk::__query_builder::Col<CharacterStatsV1, u32>,
    pub mana: __sdk::__query_builder::Col<CharacterStatsV1, u32>,
    pub capacity: __sdk::__query_builder::Col<CharacterStatsV1, u32>,
}

impl __sdk::__query_builder::HasCols for CharacterStatsV1 {
    type Cols = CharacterStatsV1Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterStatsV1Cols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            experience: __sdk::__query_builder::Col::new(table_name, "experience"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            mana: __sdk::__query_builder::Col::new(table_name, "mana"),
            capacity: __sdk::__query_builder::Col::new(table_name, "capacity"),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterStatsV1`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterStatsV1IxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterStatsV1, u64>,
    pub user_id: __sdk::__query_builder::IxCol<CharacterStatsV1, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for CharacterStatsV1 {
    type IxCols = CharacterStatsV1IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterStatsV1IxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterStatsV1 {}
