// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::{character_position_v_1_type::CharacterPositionV1, direction_v_1_type::DirectionV1};
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_position_v1`.
///
/// Obtain a handle from the [`CharacterPositionV1TableAccess::character_position_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.character_position_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_position_v_1().on_insert(...)`.
pub struct CharacterPositionV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterPositionV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_position_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterPositionV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterPositionV1TableHandle`], which mediates access to the table `character_position_v1`.
    fn character_position_v_1(&self) -> CharacterPositionV1TableHandle<'_>;
}

impl CharacterPositionV1TableAccess for super::RemoteTables {
    fn character_position_v_1(&self) -> CharacterPositionV1TableHandle<'_> {
        CharacterPositionV1TableHandle {
            imp: self.imp.get_table::<CharacterPositionV1>("character_position_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterPositionV1InsertCallbackId(__sdk::CallbackId);
pub struct CharacterPositionV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterPositionV1TableHandle<'ctx> {
    type Row = CharacterPositionV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterPositionV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterPositionV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterPositionV1InsertCallbackId {
        CharacterPositionV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterPositionV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterPositionV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterPositionV1DeleteCallbackId {
        CharacterPositionV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterPositionV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterPositionV1>("character_position_v1");
    _table.add_unique_constraint::<u64>("character_position_id", |row| &row.character_position_id);
}
pub struct CharacterPositionV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterPositionV1TableHandle<'ctx> {
    type UpdateCallbackId = CharacterPositionV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterPositionV1UpdateCallbackId {
        CharacterPositionV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterPositionV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CharacterPositionV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterPositionV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `character_position_id` unique index on the table `character_position_v1`,
/// which allows point queries on the field of the same name
/// via the [`CharacterPositionV1CharacterPositionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_position_v_1().character_position_id().find(...)`.
pub struct CharacterPositionV1CharacterPositionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterPositionV1, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterPositionV1TableHandle<'ctx> {
    /// Get a handle on the `character_position_id` unique index on the table `character_position_v1`.
    pub fn character_position_id(&self) -> CharacterPositionV1CharacterPositionIdUnique<'ctx> {
        CharacterPositionV1CharacterPositionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("character_position_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterPositionV1CharacterPositionIdUnique<'ctx> {
    /// Find the subscribed row whose `character_position_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CharacterPositionV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterPositionV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait character_position_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterPositionV1`.
    fn character_position_v1(&self) -> __sdk::__query_builder::Table<CharacterPositionV1>;
}

impl character_position_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn character_position_v1(&self) -> __sdk::__query_builder::Table<CharacterPositionV1> {
        __sdk::__query_builder::Table::new("character_position_v1")
    }
}
