// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::{gender_v_1_type::GenderV1, race_v_1_type::RaceV1};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateCharacterV1Args {
    pub display_name: String,
    pub gender: GenderV1,
    pub race: RaceV1,
}

impl From<CreateCharacterV1Args> for super::Reducer {
    fn from(args: CreateCharacterV1Args) -> Self {
        Self::CreateCharacterV1 {
            display_name: args.display_name,
            gender: args.gender,
            race: args.race,
        }
    }
}

impl __sdk::InModule for CreateCharacterV1Args {
    type Module = super::RemoteModule;
}

pub struct CreateCharacterV1CallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_character_v1`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_character_v_1 {
    /// Request that the remote module invoke the reducer `create_character_v1` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_character_v_1`] callbacks.
    fn create_character_v_1(&self, display_name: String, gender: GenderV1, race: RaceV1) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_character_v1`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateCharacterV1CallbackId`] can be passed to [`Self::remove_on_create_character_v_1`]
    /// to cancel the callback.
    fn on_create_character_v_1(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &GenderV1, &RaceV1) + Send + 'static,
    ) -> CreateCharacterV1CallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_character_v_1`],
    /// causing it not to run in the future.
    fn remove_on_create_character_v_1(&self, callback: CreateCharacterV1CallbackId);
}

impl create_character_v_1 for super::RemoteReducers {
    fn create_character_v_1(&self, display_name: String, gender: GenderV1, race: RaceV1) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "create_character_v1",
            CreateCharacterV1Args {
                display_name,
                gender,
                race,
            },
        )
    }
    fn on_create_character_v_1(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &GenderV1, &RaceV1) + Send + 'static,
    ) -> CreateCharacterV1CallbackId {
        CreateCharacterV1CallbackId(self.imp.on_reducer(
            "create_character_v1",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::CreateCharacterV1 {
                                    display_name,
                                    gender,
                                    race,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, display_name, gender, race)
            }),
        ))
    }
    fn remove_on_create_character_v_1(&self, callback: CreateCharacterV1CallbackId) {
        self.imp.remove_on_reducer("create_character_v1", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_character_v1`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_character_v_1 {
    /// Set the call-reducer flags for the reducer `create_character_v1` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_character_v_1(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_character_v_1 for super::SetReducerFlags {
    fn create_character_v_1(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_character_v1", flags);
    }
}
