// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::{gender_v_1_type::GenderV1, race_v_1_type::RaceV1};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateCharacterV1Args {
    pub display_name: String,
    pub gender: GenderV1,
    pub race: RaceV1,
}

impl From<CreateCharacterV1Args> for super::Reducer {
    fn from(args: CreateCharacterV1Args) -> Self {
        Self::CreateCharacterV1 {
            display_name: args.display_name,
            gender: args.gender,
            race: args.race,
        }
    }
}

impl __sdk::InModule for CreateCharacterV1Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_character_v1`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_character_v_1 {
    /// Request that the remote module invoke the reducer `create_character_v1` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_character_v_1:create_character_v_1_then`] to run a callback after the reducer completes.
    fn create_character_v_1(&self, display_name: String, gender: GenderV1, race: RaceV1) -> __sdk::Result<()> {
        self.create_character_v_1_then(display_name, gender, race, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_character_v1` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_character_v_1_then(
        &self,
        display_name: String,
        gender: GenderV1,
        race: RaceV1,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>) + Send + 'static,
    ) -> __sdk::Result<()>;
}

impl create_character_v_1 for super::RemoteReducers {
    fn create_character_v_1_then(
        &self,
        display_name: String,
        gender: GenderV1,
        race: RaceV1,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>) + Send + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateCharacterV1Args {
                display_name,
                gender,
                race,
            },
            callback,
        )
    }
}
