// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::current_character_v_1_type::CurrentCharacterV1;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `current_character_v1`.
///
/// Obtain a handle from the [`CurrentCharacterV1TableAccess::current_character_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.current_character_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.current_character_v_1().on_insert(...)`.
pub struct CurrentCharacterV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<CurrentCharacterV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `current_character_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CurrentCharacterV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CurrentCharacterV1TableHandle`], which mediates access to the table `current_character_v1`.
    fn current_character_v_1(&self) -> CurrentCharacterV1TableHandle<'_>;
}

impl CurrentCharacterV1TableAccess for super::RemoteTables {
    fn current_character_v_1(&self) -> CurrentCharacterV1TableHandle<'_> {
        CurrentCharacterV1TableHandle {
            imp: self.imp.get_table::<CurrentCharacterV1>("current_character_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CurrentCharacterV1InsertCallbackId(__sdk::CallbackId);
pub struct CurrentCharacterV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CurrentCharacterV1TableHandle<'ctx> {
    type Row = CurrentCharacterV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CurrentCharacterV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CurrentCharacterV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CurrentCharacterV1InsertCallbackId {
        CurrentCharacterV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CurrentCharacterV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CurrentCharacterV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CurrentCharacterV1DeleteCallbackId {
        CurrentCharacterV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CurrentCharacterV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CurrentCharacterV1>("current_character_v1");
    _table.add_unique_constraint::<__sdk::Identity>("user_id", |row| &row.user_id);
}
pub struct CurrentCharacterV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CurrentCharacterV1TableHandle<'ctx> {
    type UpdateCallbackId = CurrentCharacterV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CurrentCharacterV1UpdateCallbackId {
        CurrentCharacterV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CurrentCharacterV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CurrentCharacterV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CurrentCharacterV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user_id` unique index on the table `current_character_v1`,
/// which allows point queries on the field of the same name
/// via the [`CurrentCharacterV1UserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.current_character_v_1().user_id().find(...)`.
pub struct CurrentCharacterV1UserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CurrentCharacterV1, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CurrentCharacterV1TableHandle<'ctx> {
    /// Get a handle on the `user_id` unique index on the table `current_character_v1`.
    pub fn user_id(&self) -> CurrentCharacterV1UserIdUnique<'ctx> {
        CurrentCharacterV1UserIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("user_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CurrentCharacterV1UserIdUnique<'ctx> {
    /// Find the subscribed row whose `user_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<CurrentCharacterV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CurrentCharacterV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait current_character_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CurrentCharacterV1`.
    fn current_character_v1(&self) -> __sdk::__query_builder::Table<CurrentCharacterV1>;
}

impl current_character_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn current_character_v1(&self) -> __sdk::__query_builder::Table<CurrentCharacterV1> {
        __sdk::__query_builder::Table::new("current_character_v1")
    }
}
