// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CurrentCharacterV1 {
    pub user_id: __sdk::Identity,
    pub character_id: u64,
    pub signed_in_at: __sdk::Timestamp,
}

impl __sdk::InModule for CurrentCharacterV1 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CurrentCharacterV1`.
///
/// Provides typed access to columns for query building.
pub struct CurrentCharacterV1Cols {
    pub user_id: __sdk::__query_builder::Col<CurrentCharacterV1, __sdk::Identity>,
    pub character_id: __sdk::__query_builder::Col<CurrentCharacterV1, u64>,
    pub signed_in_at: __sdk::__query_builder::Col<CurrentCharacterV1, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for CurrentCharacterV1 {
    type Cols = CurrentCharacterV1Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CurrentCharacterV1Cols {
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            signed_in_at: __sdk::__query_builder::Col::new(table_name, "signed_in_at"),
        }
    }
}

/// Indexed column accessor struct for the table `CurrentCharacterV1`.
///
/// Provides typed access to indexed columns for query building.
pub struct CurrentCharacterV1IxCols {
    pub user_id: __sdk::__query_builder::IxCol<CurrentCharacterV1, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for CurrentCharacterV1 {
    type IxCols = CurrentCharacterV1IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CurrentCharacterV1IxCols {
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CurrentCharacterV1 {}
