// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ItemDefinitionV1 {
    pub item_id: u64,
    pub name: String,
    pub kind: String,
    pub stackable: bool,
    pub weight: u32,
    pub base_value: u32,
}

impl __sdk::InModule for ItemDefinitionV1 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ItemDefinitionV1`.
///
/// Provides typed access to columns for query building.
pub struct ItemDefinitionV1Cols {
    pub item_id: __sdk::__query_builder::Col<ItemDefinitionV1, u64>,
    pub name: __sdk::__query_builder::Col<ItemDefinitionV1, String>,
    pub kind: __sdk::__query_builder::Col<ItemDefinitionV1, String>,
    pub stackable: __sdk::__query_builder::Col<ItemDefinitionV1, bool>,
    pub weight: __sdk::__query_builder::Col<ItemDefinitionV1, u32>,
    pub base_value: __sdk::__query_builder::Col<ItemDefinitionV1, u32>,
}

impl __sdk::__query_builder::HasCols for ItemDefinitionV1 {
    type Cols = ItemDefinitionV1Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ItemDefinitionV1Cols {
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            stackable: __sdk::__query_builder::Col::new(table_name, "stackable"),
            weight: __sdk::__query_builder::Col::new(table_name, "weight"),
            base_value: __sdk::__query_builder::Col::new(table_name, "base_value"),
        }
    }
}

/// Indexed column accessor struct for the table `ItemDefinitionV1`.
///
/// Provides typed access to indexed columns for query building.
pub struct ItemDefinitionV1IxCols {
    pub item_id: __sdk::__query_builder::IxCol<ItemDefinitionV1, u64>,
}

impl __sdk::__query_builder::HasIxCols for ItemDefinitionV1 {
    type IxCols = ItemDefinitionV1IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ItemDefinitionV1IxCols {
            item_id: __sdk::__query_builder::IxCol::new(table_name, "item_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ItemDefinitionV1 {}
