// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_definition_v_1_type::ItemDefinitionV1;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `item_definition_v1`.
///
/// Obtain a handle from the [`ItemDefinitionV1TableAccess::item_definition_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.item_definition_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_definition_v_1().on_insert(...)`.
pub struct ItemDefinitionV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<ItemDefinitionV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `item_definition_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ItemDefinitionV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ItemDefinitionV1TableHandle`], which mediates access to the table `item_definition_v1`.
    fn item_definition_v_1(&self) -> ItemDefinitionV1TableHandle<'_>;
}

impl ItemDefinitionV1TableAccess for super::RemoteTables {
    fn item_definition_v_1(&self) -> ItemDefinitionV1TableHandle<'_> {
        ItemDefinitionV1TableHandle {
            imp: self.imp.get_table::<ItemDefinitionV1>("item_definition_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ItemDefinitionV1InsertCallbackId(__sdk::CallbackId);
pub struct ItemDefinitionV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ItemDefinitionV1TableHandle<'ctx> {
    type Row = ItemDefinitionV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemDefinitionV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ItemDefinitionV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDefinitionV1InsertCallbackId {
        ItemDefinitionV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ItemDefinitionV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ItemDefinitionV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDefinitionV1DeleteCallbackId {
        ItemDefinitionV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ItemDefinitionV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ItemDefinitionV1>("item_definition_v1");
    _table.add_unique_constraint::<u64>("item_id", |row| &row.item_id);
}
pub struct ItemDefinitionV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ItemDefinitionV1TableHandle<'ctx> {
    type UpdateCallbackId = ItemDefinitionV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ItemDefinitionV1UpdateCallbackId {
        ItemDefinitionV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ItemDefinitionV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ItemDefinitionV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ItemDefinitionV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `item_id` unique index on the table `item_definition_v1`,
/// which allows point queries on the field of the same name
/// via the [`ItemDefinitionV1ItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_definition_v_1().item_id().find(...)`.
pub struct ItemDefinitionV1ItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ItemDefinitionV1, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ItemDefinitionV1TableHandle<'ctx> {
    /// Get a handle on the `item_id` unique index on the table `item_definition_v1`.
    pub fn item_id(&self) -> ItemDefinitionV1ItemIdUnique<'ctx> {
        ItemDefinitionV1ItemIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("item_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ItemDefinitionV1ItemIdUnique<'ctx> {
    /// Find the subscribed row whose `item_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ItemDefinitionV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ItemDefinitionV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait item_definition_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ItemDefinitionV1`.
    fn item_definition_v1(&self) -> __sdk::__query_builder::Table<ItemDefinitionV1>;
}

impl item_definition_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn item_definition_v1(&self) -> __sdk::__query_builder::Table<ItemDefinitionV1> {
        __sdk::__query_builder::Table::new("item_definition_v1")
    }
}
