// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::{map_tile_v_1_type::MapTileV1, map_v_1_type::MapV1};
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `map_v1`.
///
/// Obtain a handle from the [`MapV1TableAccess::map_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.map_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_v_1().on_insert(...)`.
pub struct MapV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<MapV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `map_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MapV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MapV1TableHandle`], which mediates access to the table `map_v1`.
    fn map_v_1(&self) -> MapV1TableHandle<'_>;
}

impl MapV1TableAccess for super::RemoteTables {
    fn map_v_1(&self) -> MapV1TableHandle<'_> {
        MapV1TableHandle {
            imp: self.imp.get_table::<MapV1>("map_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MapV1InsertCallbackId(__sdk::CallbackId);
pub struct MapV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MapV1TableHandle<'ctx> {
    type Row = MapV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MapV1InsertCallbackId;

    fn on_insert(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> MapV1InsertCallbackId {
        MapV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MapV1DeleteCallbackId;

    fn on_delete(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> MapV1DeleteCallbackId {
        MapV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MapV1>("map_v1");
    _table.add_unique_constraint::<u64>("map_id", |row| &row.map_id);
}
pub struct MapV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MapV1TableHandle<'ctx> {
    type UpdateCallbackId = MapV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapV1UpdateCallbackId {
        MapV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MapV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MapV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `map_id` unique index on the table `map_v1`,
/// which allows point queries on the field of the same name
/// via the [`MapV1MapIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_v_1().map_id().find(...)`.
pub struct MapV1MapIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MapV1, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MapV1TableHandle<'ctx> {
    /// Get a handle on the `map_id` unique index on the table `map_v1`.
    pub fn map_id(&self) -> MapV1MapIdUnique<'ctx> {
        MapV1MapIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("map_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MapV1MapIdUnique<'ctx> {
    /// Find the subscribed row whose `map_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MapV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MapV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait map_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MapV1`.
    fn map_v1(&self) -> __sdk::__query_builder::Table<MapV1>;
}

impl map_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn map_v1(&self) -> __sdk::__query_builder::Table<MapV1> {
        __sdk::__query_builder::Table::new("map_v1")
    }
}
