// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::map_tile_v_1_type::MapTileV1;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MapV1 {
    pub map_id: u64,
    pub x: u16,
    pub y: u16,
    pub z: u16,
    pub tile: MapTileV1,
}

impl __sdk::InModule for MapV1 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MapV1`.
///
/// Provides typed access to columns for query building.
pub struct MapV1Cols {
    pub map_id: __sdk::__query_builder::Col<MapV1, u64>,
    pub x: __sdk::__query_builder::Col<MapV1, u16>,
    pub y: __sdk::__query_builder::Col<MapV1, u16>,
    pub z: __sdk::__query_builder::Col<MapV1, u16>,
    pub tile: __sdk::__query_builder::Col<MapV1, MapTileV1>,
}

impl __sdk::__query_builder::HasCols for MapV1 {
    type Cols = MapV1Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MapV1Cols {
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            tile: __sdk::__query_builder::Col::new(table_name, "tile"),
        }
    }
}

/// Indexed column accessor struct for the table `MapV1`.
///
/// Provides typed access to indexed columns for query building.
pub struct MapV1IxCols {
    pub map_id: __sdk::__query_builder::IxCol<MapV1, u64>,
}

impl __sdk::__query_builder::HasIxCols for MapV1 {
    type IxCols = MapV1IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MapV1IxCols {
            map_id: __sdk::__query_builder::IxCol::new(table_name, "map_id"),
        }
    }
}
