// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod character_position_v_1_type;
pub mod character_skill_v_1_type;
pub mod character_stats_v_1_type;
pub mod character_v_1_type;
pub mod class_v_1_type;
pub mod create_character_v_1_reducer;
pub mod current_character_v_1_type;
pub mod deferred_event_v_1_type;
pub mod direction_v_1_type;
pub mod gender_v_1_type;
pub mod item_definition_v_1_type;
pub mod map_tile_v_1_type;
pub mod map_v_1_type;
pub mod oneshot_deferred_event_v_1_type;
pub mod race_v_1_type;
pub mod select_character_v_1_reducer;
pub mod skill_v_1_type;
pub mod town_temple_v_1_type;
pub mod user_v_1_type;
pub mod vw_character_all_mine_stats_v_1_table;
pub mod vw_character_all_mine_v_1_table;
pub mod vw_character_me_stats_v_1_table;
pub mod vw_character_me_v_1_table;
pub mod vw_nearby_characters_v_1_table;
pub mod vw_user_me_v_1_table;
pub mod vw_world_map_v_1_table;
pub mod vw_world_my_character_positions_v_1_table;

pub use character_position_v_1_type::CharacterPositionV1;
pub use character_skill_v_1_type::CharacterSkillV1;
pub use character_stats_v_1_type::CharacterStatsV1;
pub use character_v_1_type::CharacterV1;
pub use class_v_1_type::ClassV1;
pub use create_character_v_1_reducer::create_character_v_1;
pub use current_character_v_1_type::CurrentCharacterV1;
pub use deferred_event_v_1_type::DeferredEventV1;
pub use direction_v_1_type::DirectionV1;
pub use gender_v_1_type::GenderV1;
pub use item_definition_v_1_type::ItemDefinitionV1;
pub use map_tile_v_1_type::MapTileV1;
pub use map_v_1_type::MapV1;
pub use oneshot_deferred_event_v_1_type::OneshotDeferredEventV1;
pub use race_v_1_type::RaceV1;
pub use select_character_v_1_reducer::select_character_v_1;
pub use skill_v_1_type::SkillV1;
pub use town_temple_v_1_type::TownTempleV1;
pub use user_v_1_type::UserV1;
pub use vw_character_all_mine_stats_v_1_table::*;
pub use vw_character_all_mine_v_1_table::*;
pub use vw_character_me_stats_v_1_table::*;
pub use vw_character_me_v_1_table::*;
pub use vw_nearby_characters_v_1_table::*;
pub use vw_user_me_v_1_table::*;
pub use vw_world_map_v_1_table::*;
pub use vw_world_my_character_positions_v_1_table::*;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    CreateCharacterV1 {
        display_name: String,
        gender: GenderV1,
        race: RaceV1,
    },
    SelectCharacterV1 {
        character_id: u64,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::CreateCharacterV1 { .. } => "create_character_v_1",
            Reducer::SelectCharacterV1 { .. } => "select_character_v_1",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::CreateCharacterV1 {
                display_name,
                gender,
                race,
            } => __sats::bsatn::to_vec(&create_character_v_1_reducer::CreateCharacterV1Args {
                display_name: display_name.clone(),
                gender: gender.clone(),
                race: race.clone(),
            }),
            Reducer::SelectCharacterV1 { character_id } => {
                __sats::bsatn::to_vec(&select_character_v_1_reducer::SelectCharacterV1Args {
                    character_id: character_id.clone(),
                })
            },
            _ => unreachable!(),
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    vw_character_all_mine_stats_v_1: __sdk::TableUpdate<CharacterStatsV1>,
    vw_character_all_mine_v_1: __sdk::TableUpdate<CharacterV1>,
    vw_character_me_stats_v_1: __sdk::TableUpdate<CharacterStatsV1>,
    vw_character_me_v_1: __sdk::TableUpdate<CharacterV1>,
    vw_nearby_characters_v_1: __sdk::TableUpdate<CharacterV1>,
    vw_user_me_v_1: __sdk::TableUpdate<UserV1>,
    vw_world_map_v_1: __sdk::TableUpdate<MapV1>,
    vw_world_my_character_positions_v_1: __sdk::TableUpdate<CharacterPositionV1>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "vw_character_all_mine_stats_v1" => db_update
                    .vw_character_all_mine_stats_v_1
                    .append(vw_character_all_mine_stats_v_1_table::parse_table_update(table_update)?),
                "vw_character_all_mine_v1" => db_update
                    .vw_character_all_mine_v_1
                    .append(vw_character_all_mine_v_1_table::parse_table_update(table_update)?),
                "vw_character_me_stats_v1" => db_update
                    .vw_character_me_stats_v_1
                    .append(vw_character_me_stats_v_1_table::parse_table_update(table_update)?),
                "vw_character_me_v1" => db_update
                    .vw_character_me_v_1
                    .append(vw_character_me_v_1_table::parse_table_update(table_update)?),
                "vw_nearby_characters_v_1" => db_update
                    .vw_nearby_characters_v_1
                    .append(vw_nearby_characters_v_1_table::parse_table_update(table_update)?),
                "vw_user_me_v_1" => db_update
                    .vw_user_me_v_1
                    .append(vw_user_me_v_1_table::parse_table_update(table_update)?),
                "vw_world_map_v_1" => db_update
                    .vw_world_map_v_1
                    .append(vw_world_map_v_1_table::parse_table_update(table_update)?),
                "vw_world_my_character_positions_v_1" => db_update
                    .vw_world_my_character_positions_v_1
                    .append(vw_world_my_character_positions_v_1_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name("table", unknown, "DatabaseUpdate").into());
                },
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(&self, cache: &mut __sdk::ClientCache<RemoteModule>) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.vw_character_all_mine_stats_v_1 = cache
            .apply_diff_to_table::<CharacterStatsV1>("vw_character_all_mine_stats_v1", &self.vw_character_all_mine_stats_v_1);
        diff.vw_character_all_mine_v_1 =
            cache.apply_diff_to_table::<CharacterV1>("vw_character_all_mine_v1", &self.vw_character_all_mine_v_1);
        diff.vw_character_me_stats_v_1 =
            cache.apply_diff_to_table::<CharacterStatsV1>("vw_character_me_stats_v1", &self.vw_character_me_stats_v_1);
        diff.vw_character_me_v_1 = cache.apply_diff_to_table::<CharacterV1>("vw_character_me_v1", &self.vw_character_me_v_1);
        diff.vw_nearby_characters_v_1 =
            cache.apply_diff_to_table::<CharacterV1>("vw_nearby_characters_v_1", &self.vw_nearby_characters_v_1);
        diff.vw_user_me_v_1 = cache.apply_diff_to_table::<UserV1>("vw_user_me_v_1", &self.vw_user_me_v_1);
        diff.vw_world_map_v_1 = cache.apply_diff_to_table::<MapV1>("vw_world_map_v_1", &self.vw_world_map_v_1);
        diff.vw_world_my_character_positions_v_1 = cache.apply_diff_to_table::<CharacterPositionV1>(
            "vw_world_my_character_positions_v_1",
            &self.vw_world_my_character_positions_v_1,
        );

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "vw_character_all_mine_stats_v1" => db_update
                    .vw_character_all_mine_stats_v_1
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "vw_character_all_mine_v1" => db_update
                    .vw_character_all_mine_v_1
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "vw_character_me_stats_v1" => db_update
                    .vw_character_me_stats_v_1
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "vw_character_me_v1" => db_update
                    .vw_character_me_v_1
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "vw_nearby_characters_v_1" => db_update
                    .vw_nearby_characters_v_1
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "vw_user_me_v_1" => db_update
                    .vw_user_me_v_1
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "vw_world_map_v_1" => db_update
                    .vw_world_map_v_1
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "vw_world_my_character_positions_v_1" => db_update
                    .vw_world_my_character_positions_v_1
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into());
                },
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "vw_character_all_mine_stats_v1" => db_update
                    .vw_character_all_mine_stats_v_1
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "vw_character_all_mine_v1" => db_update
                    .vw_character_all_mine_v_1
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "vw_character_me_stats_v1" => db_update
                    .vw_character_me_stats_v_1
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "vw_character_me_v1" => db_update
                    .vw_character_me_v_1
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "vw_nearby_characters_v_1" => db_update
                    .vw_nearby_characters_v_1
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "vw_user_me_v_1" => db_update
                    .vw_user_me_v_1
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "vw_world_map_v_1" => db_update
                    .vw_world_map_v_1
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "vw_world_my_character_positions_v_1" => db_update
                    .vw_world_my_character_positions_v_1
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into());
                },
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    vw_character_all_mine_stats_v_1: __sdk::TableAppliedDiff<'r, CharacterStatsV1>,
    vw_character_all_mine_v_1: __sdk::TableAppliedDiff<'r, CharacterV1>,
    vw_character_me_stats_v_1: __sdk::TableAppliedDiff<'r, CharacterStatsV1>,
    vw_character_me_v_1: __sdk::TableAppliedDiff<'r, CharacterV1>,
    vw_nearby_characters_v_1: __sdk::TableAppliedDiff<'r, CharacterV1>,
    vw_user_me_v_1: __sdk::TableAppliedDiff<'r, UserV1>,
    vw_world_map_v_1: __sdk::TableAppliedDiff<'r, MapV1>,
    vw_world_my_character_positions_v_1: __sdk::TableAppliedDiff<'r, CharacterPositionV1>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(&self, event: &EventContext, callbacks: &mut __sdk::DbCallbacks<RemoteModule>) {
        callbacks.invoke_table_row_callbacks::<CharacterStatsV1>(
            "vw_character_all_mine_stats_v1",
            &self.vw_character_all_mine_stats_v_1,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CharacterV1>("vw_character_all_mine_v1", &self.vw_character_all_mine_v_1, event);
        callbacks.invoke_table_row_callbacks::<CharacterStatsV1>(
            "vw_character_me_stats_v1",
            &self.vw_character_me_stats_v_1,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CharacterV1>("vw_character_me_v1", &self.vw_character_me_v_1, event);
        callbacks.invoke_table_row_callbacks::<CharacterV1>("vw_nearby_characters_v_1", &self.vw_nearby_characters_v_1, event);
        callbacks.invoke_table_row_callbacks::<UserV1>("vw_user_me_v_1", &self.vw_user_me_v_1, event);
        callbacks.invoke_table_row_callbacks::<MapV1>("vw_world_map_v_1", &self.vw_world_map_v_1, event);
        callbacks.invoke_table_row_callbacks::<CharacterPositionV1>(
            "vw_world_my_character_positions_v_1",
            &self.vw_world_my_character_positions_v_1,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
        DbView = RemoteTables,
        Reducers = RemoteReducers,
        SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
    >
{
}
impl<
    Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
> RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        vw_character_all_mine_stats_v_1_table::register_table(client_cache);
        vw_character_all_mine_v_1_table::register_table(client_cache);
        vw_character_me_stats_v_1_table::register_table(client_cache);
        vw_character_me_v_1_table::register_table(client_cache);
        vw_nearby_characters_v_1_table::register_table(client_cache);
        vw_user_me_v_1_table::register_table(client_cache);
        vw_world_map_v_1_table::register_table(client_cache);
        vw_world_my_character_positions_v_1_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "vw_character_all_mine_stats_v1",
        "vw_character_all_mine_v1",
        "vw_character_me_stats_v1",
        "vw_character_me_v1",
        "vw_nearby_characters_v_1",
        "vw_user_me_v_1",
        "vw_world_map_v_1",
        "vw_world_my_character_positions_v_1",
    ];
}
