// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::deferred_event_v_1_type::DeferredEventV1;
use super::oneshot_deferred_event_v_1_type::OneshotDeferredEventV1;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `oneshot_deferred_event_v1`.
///
/// Obtain a handle from the [`OneshotDeferredEventV1TableAccess::oneshot_deferred_event_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.oneshot_deferred_event_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.oneshot_deferred_event_v_1().on_insert(...)`.
pub struct OneshotDeferredEventV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<OneshotDeferredEventV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `oneshot_deferred_event_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait OneshotDeferredEventV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`OneshotDeferredEventV1TableHandle`], which mediates access to the table `oneshot_deferred_event_v1`.
    fn oneshot_deferred_event_v_1(&self) -> OneshotDeferredEventV1TableHandle<'_>;
}

impl OneshotDeferredEventV1TableAccess for super::RemoteTables {
    fn oneshot_deferred_event_v_1(&self) -> OneshotDeferredEventV1TableHandle<'_> {
        OneshotDeferredEventV1TableHandle {
            imp: self
                .imp
                .get_table::<OneshotDeferredEventV1>("oneshot_deferred_event_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct OneshotDeferredEventV1InsertCallbackId(__sdk::CallbackId);
pub struct OneshotDeferredEventV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for OneshotDeferredEventV1TableHandle<'ctx> {
    type Row = OneshotDeferredEventV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OneshotDeferredEventV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = OneshotDeferredEventV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OneshotDeferredEventV1InsertCallbackId {
        OneshotDeferredEventV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OneshotDeferredEventV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = OneshotDeferredEventV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OneshotDeferredEventV1DeleteCallbackId {
        OneshotDeferredEventV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OneshotDeferredEventV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<OneshotDeferredEventV1>("oneshot_deferred_event_v1");
    _table.add_unique_constraint::<u64>("job_id", |row| &row.job_id);
}
pub struct OneshotDeferredEventV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for OneshotDeferredEventV1TableHandle<'ctx> {
    type UpdateCallbackId = OneshotDeferredEventV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> OneshotDeferredEventV1UpdateCallbackId {
        OneshotDeferredEventV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: OneshotDeferredEventV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<OneshotDeferredEventV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<OneshotDeferredEventV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `job_id` unique index on the table `oneshot_deferred_event_v1`,
/// which allows point queries on the field of the same name
/// via the [`OneshotDeferredEventV1JobIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.oneshot_deferred_event_v_1().job_id().find(...)`.
pub struct OneshotDeferredEventV1JobIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<OneshotDeferredEventV1, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> OneshotDeferredEventV1TableHandle<'ctx> {
    /// Get a handle on the `job_id` unique index on the table `oneshot_deferred_event_v1`.
    pub fn job_id(&self) -> OneshotDeferredEventV1JobIdUnique<'ctx> {
        OneshotDeferredEventV1JobIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("job_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> OneshotDeferredEventV1JobIdUnique<'ctx> {
    /// Find the subscribed row whose `job_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<OneshotDeferredEventV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `OneshotDeferredEventV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait oneshot_deferred_event_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `OneshotDeferredEventV1`.
    fn oneshot_deferred_event_v1(&self) -> __sdk::__query_builder::Table<OneshotDeferredEventV1>;
}

impl oneshot_deferred_event_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn oneshot_deferred_event_v1(&self) -> __sdk::__query_builder::Table<OneshotDeferredEventV1> {
        __sdk::__query_builder::Table::new("oneshot_deferred_event_v1")
    }
}
