// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::oneshot_deferred_event_v_1_type::OneshotDeferredEventV1;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OneshotDeferredEventScheduledV1Args {
    pub timer: OneshotDeferredEventV1,
}

impl From<OneshotDeferredEventScheduledV1Args> for super::Reducer {
    fn from(args: OneshotDeferredEventScheduledV1Args) -> Self {
        Self::OneshotDeferredEventScheduledV1 { timer: args.timer }
    }
}

impl __sdk::InModule for OneshotDeferredEventScheduledV1Args {
    type Module = super::RemoteModule;
}

pub struct OneshotDeferredEventScheduledV1CallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `oneshot_deferred_event_scheduled_v1`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait oneshot_deferred_event_scheduled_v_1 {
    /// Request that the remote module invoke the reducer `oneshot_deferred_event_scheduled_v1` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_oneshot_deferred_event_scheduled_v_1`] callbacks.
    fn oneshot_deferred_event_scheduled_v_1(&self, timer: OneshotDeferredEventV1) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `oneshot_deferred_event_scheduled_v1`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`OneshotDeferredEventScheduledV1CallbackId`] can be passed to [`Self::remove_on_oneshot_deferred_event_scheduled_v_1`]
    /// to cancel the callback.
    fn on_oneshot_deferred_event_scheduled_v_1(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &OneshotDeferredEventV1) + Send + 'static,
    ) -> OneshotDeferredEventScheduledV1CallbackId;
    /// Cancel a callback previously registered by [`Self::on_oneshot_deferred_event_scheduled_v_1`],
    /// causing it not to run in the future.
    fn remove_on_oneshot_deferred_event_scheduled_v_1(&self, callback: OneshotDeferredEventScheduledV1CallbackId);
}

impl oneshot_deferred_event_scheduled_v_1 for super::RemoteReducers {
    fn oneshot_deferred_event_scheduled_v_1(&self, timer: OneshotDeferredEventV1) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "oneshot_deferred_event_scheduled_v1",
            OneshotDeferredEventScheduledV1Args { timer },
        )
    }
    fn on_oneshot_deferred_event_scheduled_v_1(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &OneshotDeferredEventV1) + Send + 'static,
    ) -> OneshotDeferredEventScheduledV1CallbackId {
        OneshotDeferredEventScheduledV1CallbackId(self.imp.on_reducer(
            "oneshot_deferred_event_scheduled_v1",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::OneshotDeferredEventScheduledV1 { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_oneshot_deferred_event_scheduled_v_1(&self, callback: OneshotDeferredEventScheduledV1CallbackId) {
        self.imp.remove_on_reducer("oneshot_deferred_event_scheduled_v1", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `oneshot_deferred_event_scheduled_v1`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_oneshot_deferred_event_scheduled_v_1 {
    /// Set the call-reducer flags for the reducer `oneshot_deferred_event_scheduled_v1` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn oneshot_deferred_event_scheduled_v_1(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_oneshot_deferred_event_scheduled_v_1 for super::SetReducerFlags {
    fn oneshot_deferred_event_scheduled_v_1(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("oneshot_deferred_event_scheduled_v1", flags);
    }
}
