// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::deferred_event_v_1_type::DeferredEventV1;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OneshotDeferredEventV1 {
    pub job_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub event: DeferredEventV1,
    pub sender: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for OneshotDeferredEventV1 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OneshotDeferredEventV1`.
///
/// Provides typed access to columns for query building.
pub struct OneshotDeferredEventV1Cols {
    pub job_id: __sdk::__query_builder::Col<OneshotDeferredEventV1, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<OneshotDeferredEventV1, __sdk::ScheduleAt>,
    pub event: __sdk::__query_builder::Col<OneshotDeferredEventV1, DeferredEventV1>,
    pub sender: __sdk::__query_builder::Col<OneshotDeferredEventV1, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<OneshotDeferredEventV1, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for OneshotDeferredEventV1 {
    type Cols = OneshotDeferredEventV1Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OneshotDeferredEventV1Cols {
            job_id: __sdk::__query_builder::Col::new(table_name, "job_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            event: __sdk::__query_builder::Col::new(table_name, "event"),
            sender: __sdk::__query_builder::Col::new(table_name, "sender"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `OneshotDeferredEventV1`.
///
/// Provides typed access to indexed columns for query building.
pub struct OneshotDeferredEventV1IxCols {
    pub job_id: __sdk::__query_builder::IxCol<OneshotDeferredEventV1, u64>,
}

impl __sdk::__query_builder::HasIxCols for OneshotDeferredEventV1 {
    type IxCols = OneshotDeferredEventV1IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OneshotDeferredEventV1IxCols {
            job_id: __sdk::__query_builder::IxCol::new(table_name, "job_id"),
        }
    }
}
