// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SelectCharacterV1Args {
    pub character_id: u64,
}

impl From<SelectCharacterV1Args> for super::Reducer {
    fn from(args: SelectCharacterV1Args) -> Self {
        Self::SelectCharacterV1 {
            character_id: args.character_id,
        }
    }
}

impl __sdk::InModule for SelectCharacterV1Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `select_character_v_1`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait select_character_v_1 {
    /// Request that the remote module invoke the reducer `select_character_v_1` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`select_character_v_1:select_character_v_1_then`] to run a callback after the reducer completes.
    fn select_character_v_1(&self, character_id: u64) -> __sdk::Result<()> {
        self.select_character_v_1_then(character_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `select_character_v_1` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn select_character_v_1_then(
        &self,
        character_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>) + Send + 'static,
    ) -> __sdk::Result<()>;
}

impl select_character_v_1 for super::RemoteReducers {
    fn select_character_v_1_then(
        &self,
        character_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>) + Send + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SelectCharacterV1Args { character_id }, callback)
    }
}
