// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TownTempleV1 {
    pub town_temple_id: u64,
    pub name: String,
    pub x: u16,
    pub y: u16,
    pub z: u16,
}

impl __sdk::InModule for TownTempleV1 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TownTempleV1`.
///
/// Provides typed access to columns for query building.
pub struct TownTempleV1Cols {
    pub town_temple_id: __sdk::__query_builder::Col<TownTempleV1, u64>,
    pub name: __sdk::__query_builder::Col<TownTempleV1, String>,
    pub x: __sdk::__query_builder::Col<TownTempleV1, u16>,
    pub y: __sdk::__query_builder::Col<TownTempleV1, u16>,
    pub z: __sdk::__query_builder::Col<TownTempleV1, u16>,
}

impl __sdk::__query_builder::HasCols for TownTempleV1 {
    type Cols = TownTempleV1Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TownTempleV1Cols {
            town_temple_id: __sdk::__query_builder::Col::new(table_name, "town_temple_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
        }
    }
}

/// Indexed column accessor struct for the table `TownTempleV1`.
///
/// Provides typed access to indexed columns for query building.
pub struct TownTempleV1IxCols {
    pub town_temple_id: __sdk::__query_builder::IxCol<TownTempleV1, u64>,
}

impl __sdk::__query_builder::HasIxCols for TownTempleV1 {
    type IxCols = TownTempleV1IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TownTempleV1IxCols {
            town_temple_id: __sdk::__query_builder::IxCol::new(table_name, "town_temple_id"),
        }
    }
}
