// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::town_v_1_type::TownV1;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `town_v1`.
///
/// Obtain a handle from the [`TownV1TableAccess::town_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.town_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.town_v_1().on_insert(...)`.
pub struct TownV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<TownV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `town_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TownV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TownV1TableHandle`], which mediates access to the table `town_v1`.
    fn town_v_1(&self) -> TownV1TableHandle<'_>;
}

impl TownV1TableAccess for super::RemoteTables {
    fn town_v_1(&self) -> TownV1TableHandle<'_> {
        TownV1TableHandle {
            imp: self.imp.get_table::<TownV1>("town_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TownV1InsertCallbackId(__sdk::CallbackId);
pub struct TownV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TownV1TableHandle<'ctx> {
    type Row = TownV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TownV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TownV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TownV1InsertCallbackId {
        TownV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TownV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TownV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TownV1DeleteCallbackId {
        TownV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TownV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TownV1>("town_v1");
    _table.add_unique_constraint::<u64>("town_id", |row| &row.town_id);
}
pub struct TownV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TownV1TableHandle<'ctx> {
    type UpdateCallbackId = TownV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TownV1UpdateCallbackId {
        TownV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TownV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TownV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TownV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `town_id` unique index on the table `town_v1`,
/// which allows point queries on the field of the same name
/// via the [`TownV1TownIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.town_v_1().town_id().find(...)`.
pub struct TownV1TownIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TownV1, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TownV1TableHandle<'ctx> {
    /// Get a handle on the `town_id` unique index on the table `town_v1`.
    pub fn town_id(&self) -> TownV1TownIdUnique<'ctx> {
        TownV1TownIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("town_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TownV1TownIdUnique<'ctx> {
    /// Find the subscribed row whose `town_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TownV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TownV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait town_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TownV1`.
    fn town_v1(&self) -> __sdk::__query_builder::Table<TownV1>;
}

impl town_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn town_v1(&self) -> __sdk::__query_builder::Table<TownV1> {
        __sdk::__query_builder::Table::new("town_v1")
    }
}
