// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::town_temple_v_1_type::TownTempleV1;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `town_temple_v1`.
///
/// Obtain a handle from the [`TownTempleV1TableAccess::town_temple_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.town_temple_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.town_temple_v_1().on_insert(...)`.
pub struct TownTempleV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<TownTempleV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `town_temple_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TownTempleV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TownTempleV1TableHandle`], which mediates access to the table `town_temple_v1`.
    fn town_temple_v_1(&self) -> TownTempleV1TableHandle<'_>;
}

impl TownTempleV1TableAccess for super::RemoteTables {
    fn town_temple_v_1(&self) -> TownTempleV1TableHandle<'_> {
        TownTempleV1TableHandle {
            imp: self.imp.get_table::<TownTempleV1>("town_temple_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TownTempleV1InsertCallbackId(__sdk::CallbackId);
pub struct TownTempleV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TownTempleV1TableHandle<'ctx> {
    type Row = TownTempleV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TownTempleV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TownTempleV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TownTempleV1InsertCallbackId {
        TownTempleV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TownTempleV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TownTempleV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TownTempleV1DeleteCallbackId {
        TownTempleV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TownTempleV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TownTempleV1>("town_temple_v1");
    _table.add_unique_constraint::<u64>("town_temple_id", |row| &row.town_temple_id);
}
pub struct TownTempleV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TownTempleV1TableHandle<'ctx> {
    type UpdateCallbackId = TownTempleV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TownTempleV1UpdateCallbackId {
        TownTempleV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TownTempleV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TownTempleV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TownTempleV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `town_temple_id` unique index on the table `town_temple_v1`,
/// which allows point queries on the field of the same name
/// via the [`TownTempleV1TownTempleIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.town_temple_v_1().town_temple_id().find(...)`.
pub struct TownTempleV1TownTempleIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TownTempleV1, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TownTempleV1TableHandle<'ctx> {
    /// Get a handle on the `town_temple_id` unique index on the table `town_temple_v1`.
    pub fn town_temple_id(&self) -> TownTempleV1TownTempleIdUnique<'ctx> {
        TownTempleV1TownTempleIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("town_temple_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TownTempleV1TownTempleIdUnique<'ctx> {
    /// Find the subscribed row whose `town_temple_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TownTempleV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TownTempleV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait town_temple_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TownTempleV1`.
    fn town_temple_v1(&self) -> __sdk::__query_builder::Table<TownTempleV1>;
}

impl town_temple_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn town_temple_v1(&self) -> __sdk::__query_builder::Table<TownTempleV1> {
        __sdk::__query_builder::Table::new("town_temple_v1")
    }
}
