// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TownV1 {
    pub town_id: u64,
    pub name: String,
    pub temple_x: u16,
    pub temple_y: u16,
    pub temple_z: u16,
}

impl __sdk::InModule for TownV1 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TownV1`.
///
/// Provides typed access to columns for query building.
pub struct TownV1Cols {
    pub town_id: __sdk::__query_builder::Col<TownV1, u64>,
    pub name: __sdk::__query_builder::Col<TownV1, String>,
    pub temple_x: __sdk::__query_builder::Col<TownV1, u16>,
    pub temple_y: __sdk::__query_builder::Col<TownV1, u16>,
    pub temple_z: __sdk::__query_builder::Col<TownV1, u16>,
}

impl __sdk::__query_builder::HasCols for TownV1 {
    type Cols = TownV1Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TownV1Cols {
            town_id: __sdk::__query_builder::Col::new(table_name, "town_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            temple_x: __sdk::__query_builder::Col::new(table_name, "temple_x"),
            temple_y: __sdk::__query_builder::Col::new(table_name, "temple_y"),
            temple_z: __sdk::__query_builder::Col::new(table_name, "temple_z"),
        }
    }
}

/// Indexed column accessor struct for the table `TownV1`.
///
/// Provides typed access to indexed columns for query building.
pub struct TownV1IxCols {
    pub town_id: __sdk::__query_builder::IxCol<TownV1, u64>,
}

impl __sdk::__query_builder::HasIxCols for TownV1 {
    type IxCols = TownV1IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TownV1IxCols {
            town_id: __sdk::__query_builder::IxCol::new(table_name, "town_id"),
        }
    }
}
