// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_v_1_type::UserV1;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_v1`.
///
/// Obtain a handle from the [`UserV1TableAccess::user_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.user_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_v_1().on_insert(...)`.
pub struct UserV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<UserV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserV1TableHandle`], which mediates access to the table `user_v1`.
    fn user_v_1(&self) -> UserV1TableHandle<'_>;
}

impl UserV1TableAccess for super::RemoteTables {
    fn user_v_1(&self) -> UserV1TableHandle<'_> {
        UserV1TableHandle {
            imp: self.imp.get_table::<UserV1>("user_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserV1InsertCallbackId(__sdk::CallbackId);
pub struct UserV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserV1TableHandle<'ctx> {
    type Row = UserV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserV1InsertCallbackId {
        UserV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserV1DeleteCallbackId {
        UserV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserV1>("user_v1");
    _table.add_unique_constraint::<__sdk::Identity>("user_id", |row| &row.user_id);
}
pub struct UserV1UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserV1TableHandle<'ctx> {
    type UpdateCallbackId = UserV1UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserV1UpdateCallbackId {
        UserV1UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserV1UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UserV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user_id` unique index on the table `user_v1`,
/// which allows point queries on the field of the same name
/// via the [`UserV1UserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_v_1().user_id().find(...)`.
pub struct UserV1UserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserV1, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserV1TableHandle<'ctx> {
    /// Get a handle on the `user_id` unique index on the table `user_v1`.
    pub fn user_id(&self) -> UserV1UserIdUnique<'ctx> {
        UserV1UserIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("user_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserV1UserIdUnique<'ctx> {
    /// Find the subscribed row whose `user_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<UserV1> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserV1`.
    fn user_v1(&self) -> __sdk::__query_builder::Table<UserV1>;
}

impl user_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn user_v1(&self) -> __sdk::__query_builder::Table<UserV1> {
        __sdk::__query_builder::Table::new("user_v1")
    }
}
