// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_stats_v_1_type::CharacterStatsV1;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `vw_character_all_mine_stats_v_1`.
///
/// Obtain a handle from the [`VwCharacterAllMineStatsV1TableAccess::vw_character_all_mine_stats_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.vw_character_all_mine_stats_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.vw_character_all_mine_stats_v_1().on_insert(...)`.
pub struct VwCharacterAllMineStatsV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterStatsV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `vw_character_all_mine_stats_v_1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VwCharacterAllMineStatsV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VwCharacterAllMineStatsV1TableHandle`], which mediates access to the table `vw_character_all_mine_stats_v_1`.
    fn vw_character_all_mine_stats_v_1(&self) -> VwCharacterAllMineStatsV1TableHandle<'_>;
}

impl VwCharacterAllMineStatsV1TableAccess for super::RemoteTables {
    fn vw_character_all_mine_stats_v_1(&self) -> VwCharacterAllMineStatsV1TableHandle<'_> {
        VwCharacterAllMineStatsV1TableHandle {
            imp: self.imp.get_table::<CharacterStatsV1>("vw_character_all_mine_stats_v_1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VwCharacterAllMineStatsV1InsertCallbackId(__sdk::CallbackId);
pub struct VwCharacterAllMineStatsV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VwCharacterAllMineStatsV1TableHandle<'ctx> {
    type Row = CharacterStatsV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterStatsV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VwCharacterAllMineStatsV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VwCharacterAllMineStatsV1InsertCallbackId {
        VwCharacterAllMineStatsV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VwCharacterAllMineStatsV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VwCharacterAllMineStatsV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VwCharacterAllMineStatsV1DeleteCallbackId {
        VwCharacterAllMineStatsV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VwCharacterAllMineStatsV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterStatsV1>("vw_character_all_mine_stats_v_1");
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<CharacterStatsV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterStatsV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterStatsV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait vw_character_all_mine_stats_v_1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterStatsV1`.
    fn vw_character_all_mine_stats_v_1(&self) -> __sdk::__query_builder::Table<CharacterStatsV1>;
}

impl vw_character_all_mine_stats_v_1QueryTableAccess for __sdk::QueryTableAccessor {
    fn vw_character_all_mine_stats_v_1(&self) -> __sdk::__query_builder::Table<CharacterStatsV1> {
        __sdk::__query_builder::Table::new("vw_character_all_mine_stats_v_1")
    }
}
