// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_v_1_type::UserV1;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `vw_my_user_v1`.
///
/// Obtain a handle from the [`VwMyUserV1TableAccess::vw_my_user_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.vw_my_user_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.vw_my_user_v_1().on_insert(...)`.
pub struct VwMyUserV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<UserV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `vw_my_user_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VwMyUserV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VwMyUserV1TableHandle`], which mediates access to the table `vw_my_user_v1`.
    fn vw_my_user_v_1(&self) -> VwMyUserV1TableHandle<'_>;
}

impl VwMyUserV1TableAccess for super::RemoteTables {
    fn vw_my_user_v_1(&self) -> VwMyUserV1TableHandle<'_> {
        VwMyUserV1TableHandle {
            imp: self.imp.get_table::<UserV1>("vw_my_user_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VwMyUserV1InsertCallbackId(__sdk::CallbackId);
pub struct VwMyUserV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VwMyUserV1TableHandle<'ctx> {
    type Row = UserV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VwMyUserV1InsertCallbackId;

    fn on_insert(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> VwMyUserV1InsertCallbackId {
        VwMyUserV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VwMyUserV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VwMyUserV1DeleteCallbackId;

    fn on_delete(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> VwMyUserV1DeleteCallbackId {
        VwMyUserV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VwMyUserV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserV1>("vw_my_user_v1");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UserV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait vw_my_user_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserV1`.
    fn vw_my_user_v1(&self) -> __sdk::__query_builder::Table<UserV1>;
}

impl vw_my_user_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn vw_my_user_v1(&self) -> __sdk::__query_builder::Table<UserV1> {
        __sdk::__query_builder::Table::new("vw_my_user_v1")
    }
}
