// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_v_1_type::UserV1;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `vw_user_me_v_1`.
///
/// Obtain a handle from the [`VwUserMeV1TableAccess::vw_user_me_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.vw_user_me_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.vw_user_me_v_1().on_insert(...)`.
pub struct VwUserMeV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<UserV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `vw_user_me_v_1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VwUserMeV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VwUserMeV1TableHandle`], which mediates access to the table `vw_user_me_v_1`.
    fn vw_user_me_v_1(&self) -> VwUserMeV1TableHandle<'_>;
}

impl VwUserMeV1TableAccess for super::RemoteTables {
    fn vw_user_me_v_1(&self) -> VwUserMeV1TableHandle<'_> {
        VwUserMeV1TableHandle {
            imp: self.imp.get_table::<UserV1>("vw_user_me_v_1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VwUserMeV1InsertCallbackId(__sdk::CallbackId);
pub struct VwUserMeV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VwUserMeV1TableHandle<'ctx> {
    type Row = UserV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VwUserMeV1InsertCallbackId;

    fn on_insert(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> VwUserMeV1InsertCallbackId {
        VwUserMeV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VwUserMeV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VwUserMeV1DeleteCallbackId;

    fn on_delete(&self, callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static) -> VwUserMeV1DeleteCallbackId {
        VwUserMeV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VwUserMeV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserV1>("vw_user_me_v_1");
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<UserV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait vw_user_me_v_1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserV1`.
    fn vw_user_me_v_1(&self) -> __sdk::__query_builder::Table<UserV1>;
}

impl vw_user_me_v_1QueryTableAccess for __sdk::QueryTableAccessor {
    fn vw_user_me_v_1(&self) -> __sdk::__query_builder::Table<UserV1> {
        __sdk::__query_builder::Table::new("vw_user_me_v_1")
    }
}
