// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::{character_position_v_1_type::CharacterPositionV1, direction_v_1_type::DirectionV1};
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `vw_world_my_character_positions_v1`.
///
/// Obtain a handle from the [`VwWorldMyCharacterPositionsV1TableAccess::vw_world_my_character_positions_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.vw_world_my_character_positions_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.vw_world_my_character_positions_v_1().on_insert(...)`.
pub struct VwWorldMyCharacterPositionsV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterPositionV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `vw_world_my_character_positions_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VwWorldMyCharacterPositionsV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VwWorldMyCharacterPositionsV1TableHandle`], which mediates access to the table `vw_world_my_character_positions_v1`.
    fn vw_world_my_character_positions_v_1(&self) -> VwWorldMyCharacterPositionsV1TableHandle<'_>;
}

impl VwWorldMyCharacterPositionsV1TableAccess for super::RemoteTables {
    fn vw_world_my_character_positions_v_1(&self) -> VwWorldMyCharacterPositionsV1TableHandle<'_> {
        VwWorldMyCharacterPositionsV1TableHandle {
            imp: self
                .imp
                .get_table::<CharacterPositionV1>("vw_world_my_character_positions_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VwWorldMyCharacterPositionsV1InsertCallbackId(__sdk::CallbackId);
pub struct VwWorldMyCharacterPositionsV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VwWorldMyCharacterPositionsV1TableHandle<'ctx> {
    type Row = CharacterPositionV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterPositionV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VwWorldMyCharacterPositionsV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VwWorldMyCharacterPositionsV1InsertCallbackId {
        VwWorldMyCharacterPositionsV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VwWorldMyCharacterPositionsV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VwWorldMyCharacterPositionsV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VwWorldMyCharacterPositionsV1DeleteCallbackId {
        VwWorldMyCharacterPositionsV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VwWorldMyCharacterPositionsV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterPositionV1>("vw_world_my_character_positions_v1");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CharacterPositionV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterPositionV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterPositionV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait vw_world_my_character_positions_v1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterPositionV1`.
    fn vw_world_my_character_positions_v1(&self) -> __sdk::__query_builder::Table<CharacterPositionV1>;
}

impl vw_world_my_character_positions_v1QueryTableAccess for __sdk::QueryTableAccessor {
    fn vw_world_my_character_positions_v1(&self) -> __sdk::__query_builder::Table<CharacterPositionV1> {
        __sdk::__query_builder::Table::new("vw_world_my_character_positions_v1")
    }
}
