// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::{map_tile_v_1_type::MapTileV1, map_v_1_type::MapV1};
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `vw_world_map_v1`.
///
/// Obtain a handle from the [`VwWorldMapV1TableAccess::vw_world_map_v_1`] method on [`super::RemoteTables`],
/// like `ctx.db.vw_world_map_v_1()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.vw_world_map_v_1().on_insert(...)`.
pub struct VwWorldMapV1TableHandle<'ctx> {
    imp: __sdk::TableHandle<MapV1>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `vw_world_map_v1`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VwWorldMapV1TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VwWorldMapV1TableHandle`], which mediates access to the table `vw_world_map_v1`.
    fn vw_world_map_v_1(&self) -> VwWorldMapV1TableHandle<'_>;
}

impl VwWorldMapV1TableAccess for super::RemoteTables {
    fn vw_world_map_v_1(&self) -> VwWorldMapV1TableHandle<'_> {
        VwWorldMapV1TableHandle {
            imp: self.imp.get_table::<MapV1>("vw_world_map_v1"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VwWorldMapV1InsertCallbackId(__sdk::CallbackId);
pub struct VwWorldMapV1DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VwWorldMapV1TableHandle<'ctx> {
    type Row = MapV1;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapV1> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VwWorldMapV1InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VwWorldMapV1InsertCallbackId {
        VwWorldMapV1InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VwWorldMapV1InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VwWorldMapV1DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VwWorldMapV1DeleteCallbackId {
        VwWorldMapV1DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VwWorldMapV1DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MapV1>("vw_world_map_v1");
}

#[doc(hidden)]
pub(super) fn parse_table_update(raw_updates: __ws::v2::TableUpdate) -> __sdk::Result<__sdk::TableUpdate<MapV1>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MapV1>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MapV1`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait vw_world_map_v_1QueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MapV1`.
    fn vw_world_map_v_1(&self) -> __sdk::__query_builder::Table<MapV1>;
}

impl vw_world_map_v_1QueryTableAccess for __sdk::QueryTableAccessor {
    fn vw_world_map_v_1(&self) -> __sdk::__query_builder::Table<MapV1> {
        __sdk::__query_builder::Table::new("vw_world_map_v1")
    }
}
