version: '3'

tasks:
  sdk-rust:
    desc: Generate Rust types into sdks/types/src/autogen
    cmds:
      - rm -rf sdks/types/src/autogen
      - mkdir -p sdks/types/src/autogen
      - spacetime generate --lang rust --out-dir sdks/types/src/autogen --module-path bins/world-draconis-ikariadb

  fmt:
    desc: Format all workspace code
    cmds:
      - cargo fmt --all

  check:
    desc: Check all workspace targets
    deps: [fmt]
    cmds:
      - cargo clippy --workspace --all-targets
      - cargo check --workspace --all-targets

  test:
    desc: Run all workspace tests
    deps: [check]
    cmds:
      - cargo test --workspace

  build:
    desc: Build server wasm targets
    cmds:
      - task sdk-rust
      - task check
      - cargo build -p world-alpha-ikariadb --target wasm32-unknown-unknown
      - cargo build -p world-draconis-ikariadb --target wasm32-unknown-unknown
      - cargo build --workspace --exclude world-alpha-ikariadb --exclude world-draconis-ikariadb