// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from 'spacetimedb';

// Import all reducer arg schemas
import CreateCharacterV1Reducer from '../create_character_v_1_reducer';
import MoveCharacterV1Reducer from '../move_character_v_1_reducer';
import SelectCharacterV1Reducer from '../select_character_v_1_reducer';

export type CreateCharacterV1Params = __Infer<typeof CreateCharacterV1Reducer>;
export type MoveCharacterV1Params = __Infer<typeof MoveCharacterV1Reducer>;
export type SelectCharacterV1Params = __Infer<typeof SelectCharacterV1Reducer>;
