// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MapTileV1,
} from "./types";


export default __t.row({
  mapId: __t.u64().name("map_id"),
  sectorKey: __t.u64().name("sector_key"),
  x1: __t.u16(),
  y1: __t.u16(),
  x2: __t.u16(),
  y2: __t.u16(),
  z: __t.u8(),
  get tile() {
    return MapTileV1;
  },
});
