// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DirectionV1,
} from "./types";


export default __t.row({
  characterId: __t.u64().name("character_id"),
  x: __t.u16(),
  y: __t.u16(),
  z: __t.u16(),
  get direction() {
    return DirectionV1;
  },
  updatedAt: __t.timestamp().name("updated_at"),
});
