pub const KG_TO_G: u32 = 1000;

pub const CHARACTER_NAME_MIN_LEN: usize = 4;
pub const CHARACTER_NAME_MAX_LEN: usize = 32;

pub const DEFAULT_CHARACTER_LEVEL: u16 = 1;
pub const DEFAULT_CHARACTER_EXPERIENCE: u64 = 0;
pub const DEFAULT_CHARACTER_HEALTH: u32 = 120;
pub const DEFAULT_CHARACTER_MANA: u32 = 60;
pub const DEFAULT_CHARACTER_CAPACITY: u32 = 15 * KG_TO_G;

pub const DEFAULT_SPAWN_X: u16 = 1152;
pub const DEFAULT_SPAWN_Y: u16 = 1152;

pub const MAP_VIEW_RADIUS: u16 = 11;
